import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { NavBar } from '@/app/components/navbar'
import '@/styles/globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Jonas Flores CV',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
<html lang="en">
<body className="overflow-hidden">

  <div className='grid grid-cols-1 lg:grid-cols-12 grid-rows-[3.5rem_auto] lg:grid-rows-none h-screen'>
    
    <aside className='lg:col-span-3'>
      <NavBar/>
    </aside>

    <main className="lg:col-span-9 overflow-y-auto touch-auto">
      <div className="mx-auto px-1 sm:px-3 md:px-6 lg:px-10 mt-2 mb-12 w-full ">
        <div className="rounded-md p-px shadow-md shadow-slate-500">
          <div className="rounded-xl p-3.5 bg-white pb-20">
            {children}
          </div>
        </div>
      </div>
    </main>

  </div>
</body>
</html>
  )
}